# Generated by Django 5.2.3 on 2025-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='day',
            field=models.CharField(default='Monday', max_length=20),
        ),
    ]
