# Generated by Django 5.2.3 on 2025-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_volume_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
